<template>
  <div id="main">
    <div id="title">emoji</div>
    <div id="card" ref="emoji" @mouseover="show">
      <div class="emoji card">😀</div>
      <div class="emoji card">😂</div>
      <div class="emoji card">🤣</div>
      <div class="emoji card">😄</div>
      <div class="emoji card">😅</div>
      <div class="emoji card">😆</div>
      <div class="emoji card">😉</div>
      <div class="emoji card">😊</div>
      <div class="emoji card">😋</div>
      <div class="emoji card">😎</div>
      <div class="emoji card">😍</div>
      <div class="emoji card">😘</div>
      <div class="emoji card">🥰</div>
      <div class="emoji card">😗</div>
      <div class="emoji card">😙</div>
      <div class="emoji card">😚</div>
      <div class="emoji card">🙂</div>
      <div class="emoji card">🤗</div>
      <div class="emoji card">🤩</div>
      <div class="emoji card">🤔</div>
      <div class="emoji card">🤨</div>
      <div class="emoji card">😐</div>
      <div class="emoji card">😑</div>
      <div class="emoji card">😶</div>
      <div class="emoji card">😮</div>
      <div class="emoji card">🙄</div>
      <div class="emoji card">😏</div>
      <div class="emoji card">😣</div>
      <div class="emoji card">😥</div>
      <div class="emoji card">😮</div>
      <div class="emoji card">🤐</div>
      <div class="emoji card">😯</div>
      <div class="emoji card">😪</div>
      <div class="emoji card">😫</div>
      <div class="emoji card">🥱</div>
      <div class="emoji card">😴</div>
      <div class="emoji card">😌</div>
      <div class="emoji card">😛</div>
      <div class="emoji card">😜</div>
      <div class="emoji card">😝</div>
      <div class="emoji card">🤤</div>
      <div class="emoji card">😒</div>
      <div class="emoji card">😓</div>
      <div class="emoji card">😔</div>
      <div class="emoji card">😕</div>
      <div class="emoji card">🙃</div>
      <div class="emoji card">😤</div>
      <div class="emoji card">😟</div>
      <div class="emoji card">😞</div>
      <div class="emoji card">😖</div>
      <div class="emoji card">🙁</div>
      <div class="emoji card">😲</div>
      <div class="emoji card">🤑</div>
      <div class="emoji card">🥶</div>
      <div class="emoji card">🤢</div>
      <div class="emoji card">🤬</div>
      <div class="emoji card">😡</div>
      <div class="emoji card">🤡</div>
      <div class="emoji card">😈</div>
      <div class="emoji card">👿</div>
      <div class="emoji card">💩</div>
      <div class="emoji card">👹</div>
      <div class="emoji card">👺</div>
      <div class="emoji card">💀</div>
      <div class="emoji card">🤖</div>
      <div class="emoji card">👾</div>
      <div class="emoji card">👽</div>
      <div class="emoji card">👻</div>
      <div class="emoji card">☠</div>
    </div>
    <div id="card" ref="animal" @mouseover="show">
      <div class="animal card">😺</div>
      <div class="animal card">😸</div>
      <div class="animal card">😹</div>
      <div class="animal card">😻</div>
      <div class="animal card">😼</div>
      <div class="animal card">😽</div>
      <div class="animal card">🙀</div>
      <div class="animal card">😿</div>
      <div class="animal card">😾</div>
      <div class="animal card">🐱‍👤</div>
      <div class="animal card">🐱‍🏍</div>
      <div class="animal card">🐱‍💻</div>
      <div class="animal card">🐱‍🐉</div>
      <div class="animal card">🐱‍👓</div>
      <div class="animal card">🐱‍🚀</div>
      <div class="animal card">🙈</div>
      <div class="animal card">🙉</div>
      <div class="animal card">🙊</div>
      <div class="animal card">🐵</div>
      <div class="animal card">🐶</div>
      <div class="animal card">🐺</div>
      <div class="animal card">🐱</div>
      <div class="animal card">🦁</div>
      <div class="animal card">🐯</div>
      <div class="animal card">🦒</div>
      <div class="animal card">🦊</div>
      <div class="animal card">🦝</div>
      <div class="animal card">🐮</div>
      <div class="animal card">🐷</div>
      <div class="animal card">🐗</div>
      <div class="animal card">🐭</div>
      <div class="animal card">🐹</div>
      <div class="animal card">🐰</div>
      <div class="animal card">🐻</div>
      <div class="animal card">🐨</div>
      <div class="animal card">🐼</div>
      <div class="animal card">🐸</div>
      <div class="animal card">🦓</div>
      <div class="animal card">🐴</div>
      <div class="animal card">🦄</div>
      <div class="animal card">🐔</div>
      <div class="animal card">🐲</div>
      <div class="animal card">🐒</div>
      <div class="animal card">🐽</div>
      <div class="animal card">🐾</div>
      <div class="animal card">🦍</div>
      <div class="animal card">🦧</div>
      <div class="animal card">🦮</div>
      <div class="animal card">🐕‍🦺</div>
      <div class="animal card">🐩</div>
      <div class="animal card">🐕</div>
      <div class="animal card">🐈</div>
      <div class="animal card">🐅</div>
      <div class="animal card">🐆</div>
      <div class="animal card">🐎</div>
      <div class="animal card">🦌</div>
      <div class="animal card">🦏</div>
      <div class="animal card">🦛</div>
      <div class="animal card">🐪</div>
      <div class="animal card">🐐</div>
      <div class="animal card">🐑</div>
      <div class="animal card">🐏</div>
      <div class="animal card">🐄</div>
      <div class="animal card">🐖</div>
      <div class="animal card">🐃</div>
      <div class="animal card">🐂</div>
      <div class="animal card">🦘</div>
      <div class="animal card">🦥</div>
      <div class="animal card">🦨</div>
      <div class="animal card">🦡</div>
      <div class="animal card">🐘</div>
      <div class="animal card">🐁</div>
      <div class="animal card">🐍</div>
      <div class="animal card">🐢</div>
      <div class="animal card">🐊</div>
      <div class="animal card">🦎</div>
      <div class="animal card">🐇</div>
      <div class="animal card">🦔</div>
      <div class="animal card">🐀</div>
      <div class="animal card">🐋</div>
      <div class="animal card">🐳</div>
      <div class="animal card">🐬</div>
      <div class="animal card">🦈</div>
      <div class="animal card">🦦</div>
      <div class="animal card">🦖</div>
      <div class="animal card">🦕</div>
      <div class="animal card">🐉</div>
      <div class="animal card">🦀</div>
      <div class="animal card">🦞</div>
      <div class="animal card">🐙</div>
      <div class="animal card">🦑</div>
      <div class="animal card">🦐</div>
      <div class="animal card">🐡</div>
      <div class="animal card">🐠</div>
      <div class="animal card">🐟</div>
      <div class="animal card">🦜</div>
      <div class="animal card">🦢</div>
      <div class="animal card">🕊</div>
      <div class="animal card">🦅</div>
      <div class="animal card">🦃</div>
      <div class="animal card">🐓</div>
      <div class="animal card">🦆</div>
      <div class="animal card">🐚</div>
      <div class="animal card">🐣</div>
      <div class="animal card">🐤</div>
      <div class="animal card">🐥</div>
      <div class="animal card">🐧</div>
      <div class="animal card">🐦</div>
      <div class="animal card">🦉</div>
      <div class="animal card">🦚</div>
      <div class="animal card">🦩</div>
      <div class="animal card">🕷</div>
      <div class="animal card">🦂</div>
      <div class="animal card">🦉</div>
      <div class="animal card">🐞</div>
      <div class="animal card">🐜</div>
      <div class="animal card">🐝</div>
      <div class="animal card">🦗</div>
      <div class="animal card">🦟</div>
      <div class="animal card">🐛</div>
      <div class="animal card">🐌</div>
      <div class="animal card">🦇</div>
      <div class="animal card">🦋</div>
    </div>
    <div id="card" ref="food" @mouseover="show">
      <div class="food card">🍕</div>
      <div class="food card">🍔</div>
      <div class="food card">🍟</div>
      <div class="food card">🌭</div>
      <div class="food card">🍿</div>
      <div class="food card">🧂</div>
      <div class="food card">🥓</div>
      <div class="food card">🥚</div>
      <div class="food card">🥯</div>
      <div class="food card">🥨</div>
      <div class="food card">🥐</div>
      <div class="food card">🍞</div>
      <div class="food card">🧈</div>
      <div class="food card">🥞</div>
      <div class="food card">🧇</div>
      <div class="food card">🍳</div>
      <div class="food card">🥖</div>
      <div class="food card">🧀</div>
      <div class="food card">🥗</div>
      <div class="food card">🥙</div>
      <div class="food card">🥪</div>
      <div class="food card">🌮</div>
      <div class="food card">🌯</div>
      <div class="food card">🥫</div>
      <div class="food card">🍱</div>
      <div class="food card">🥡</div>
      <div class="food card">🥠</div>
      <div class="food card">🥟</div>
      <div class="food card">🍠</div>
      <div class="food card">🥩</div>
      <div class="food card">🍗</div>
      <div class="food card">🍖</div>
      <div class="food card">🍤</div>
      <div class="food card">🍣</div>
      <div class="food card">🦪</div>
      <div class="food card">🍜</div>
      <div class="food card">🍛</div>
      <div class="food card">🍚</div>
      <div class="food card">🍙</div>
      <div class="food card">🍘</div>
      <div class="food card">🥣</div>
      <div class="food card">🍝</div>
      <div class="food card">🍲</div>
      <div class="food card">🥘</div>
      <div class="food card">🧆</div>
      <div class="food card">🍢</div>
      <div class="food card">🥮</div>
      <div class="food card">🍥</div>
      <div class="food card">🍰</div>
      <div class="food card">🎂</div>
      <div class="food card">🍪</div>
      <div class="food card">🍩</div>
      <div class="food card">🍨</div>
      <div class="food card">🍧</div>
      <div class="food card">🍦</div>
      <div class="food card">🥧</div>
      <div class="food card">🍼</div>
      <div class="food card">🍯</div>
      <div class="food card">🍮</div>
      <div class="food card">🍡</div>
      <div class="food card">🍭</div>
      <div class="food card">🍬</div>
      <div class="food card">🍫</div>
      <div class="food card">🧁</div>
      <div class="food card">🍷</div>
      <div class="food card">🍾</div>
      <div class="food card">🍶</div>
      <div class="food card">🧉</div>
      <div class="food card">🍵</div>
      <div class="food card">☕</div>
      <div class="food card">🥛</div>
      <div class="food card">🥤</div>
      <div class="food card">🧊</div>
      <div class="food card">🥃</div>
      <div class="food card">🥂</div>
      <div class="food card">🍻</div>
      <div class="food card">🍺</div>
      <div class="food card">🍹</div>
      <div class="food card">🍸</div>
      <div class="food card">🍇</div>
      <div class="food card">🍸</div>
      <div class="food card">🥥</div>
      <div class="food card">🥝</div>
      <div class="food card">🥄</div>
      <div class="food card">🍴</div>
      <div class="food card">🍽</div>
    </div>
    <div id="card" ref="plant" @mouseover="show">
      <div class="plant card">🏺</div>
      <div class="plant card">🥝</div>
      <div class="plant card">🥥</div>
      <div class="plant card">🍇</div>
      <div class="plant card">🍎</div>
      <div class="plant card">🥭</div>
      <div class="plant card">🍍</div>
      <div class="plant card">🍌</div>
      <div class="plant card">🍑</div>
      <div class="plant card">🍋</div>
      <div class="plant card">🍊</div>
      <div class="plant card">🍉</div>
      <div class="plant card">🍈</div>
      <div class="plant card">🌽</div>
      <div class="plant card">🍆</div>
      <div class="plant card">🍅</div>
      <div class="plant card">🍓</div>
      <div class="plant card">🍒</div>
      <div class="plant card">🍐</div>
      <div class="plant card">🍏</div>
      <div class="plant card">🧄</div>
      <div class="plant card">🥔</div>
      <div class="plant card">🥦</div>
      <div class="plant card">🥬</div>
      <div class="plant card">🥒</div>
      <div class="plant card">🥑</div>
      <div class="plant card">🍄</div>
      <div class="plant card">🌹</div>
      <div class="plant card">🌶</div>
      <div class="plant card">🏵</div>
      <div class="plant card">🌸</div>
      <div class="plant card">💐</div>
      <div class="plant card">🥜</div>
      <div class="plant card">🌰</div>
      <div class="plant card">🥕</div>
      <div class="plant card">🧅</div>
      <div class="plant card">🌲</div>
      <div class="plant card">🌱</div>
      <div class="plant card">☘</div>
      <div class="plant card">🥀</div>
      <div class="plant card">🌷</div>
      <div class="plant card">🌼</div>
      <div class="plant card">🌻</div>
      <div class="plant card">🌺</div>
      <div class="plant card">🍂</div>
      <div class="plant card">🍁</div>
      <div class="plant card">🍀</div>
      <div class="plant card">🌿</div>
      <div class="plant card">🌾</div>
      <div class="plant card">🌵</div>
      <div class="plant card">🌴</div>
      <div class="plant card">🌳</div>
      <div class="plant card">🍃</div>
    </div>
    <div id="card" ref="traffic" @mouseover="show">
      <div class="traffic card">🚗</div>
      <div class="traffic card">🚓</div>
      <div class="traffic card">🚕</div>
      <div class="traffic card">🛺</div>
      <div class="traffic card">🚙</div>
      <div class="traffic card">🚌</div>
      <div class="traffic card">🚐</div>
      <div class="traffic card">🚎</div>
      <div class="traffic card">🚖</div>
      <div class="traffic card">🚔</div>
      <div class="traffic card">🚘</div>
      <div class="traffic card">🚜</div>
      <div class="traffic card">🚛</div>
      <div class="traffic card">🚚</div>
      <div class="traffic card">🚒</div>
      <div class="traffic card">🚑</div>
      <div class="traffic card">🏍</div>
      <div class="traffic card">🛵</div>
      <div class="traffic card">🛴</div>
      <div class="traffic card">🚲</div>
      <div class="traffic card">🛹</div>
      <div class="traffic card">🦼</div>
      <div class="traffic card">🦽</div>
      <div class="traffic card">🚍</div>
      <div class="traffic card">🚋</div>
      <div class="traffic card">🚃</div>
      <div class="traffic card">🚞</div>
      <div class="traffic card">🚃</div>
      <div class="traffic card">🚝</div>
      <div class="traffic card">🚈</div>
      <div class="traffic card">🚅</div>
      <div class="traffic card">🚄</div>
      <div class="traffic card">🏎</div>
      <div class="traffic card">🚂</div>
      <div class="traffic card">🚡</div>
      <div class="traffic card">🚠</div>
      <div class="traffic card">🚟</div>
      <div class="traffic card">🚇</div>
      <div class="traffic card">🚊</div>
      <div class="traffic card">🚉</div>
      <div class="traffic card">🚆</div>
      <div class="traffic card">🚀</div>
      <div class="traffic card">🚁</div>
      <div class="traffic card">💺</div>
      <div class="traffic card">🛬</div>
      <div class="traffic card">🛫</div>
      <div class="traffic card">✈</div>
      <div class="traffic card">🪂</div>
      <div class="traffic card">🛩</div>
      <div class="traffic card">🚢</div>
      <div class="traffic card">🛳</div>
      <div class="traffic card">⛴</div>
      <div class="traffic card">🛥</div>
      <div class="traffic card">🚤</div>
      <div class="traffic card">⛵</div>
      <div class="traffic card">🛰</div>
      <div class="traffic card">🛸</div>
      <div class="traffic card">🏁</div>
      <div class="traffic card">🚧</div>
      <div class="traffic card">🚦</div>
      <div class="traffic card">🚥</div>
      <div class="traffic card">🚨</div>
      <div class="traffic card">⛽</div>
      <div class="traffic card">🚏</div>
      <div class="traffic card">⚓</div>
    </div>
    <div id="card" ref="place" @mouseover="show">
      <div class="place card">🏳‍🌈</div>
      <div class="place card">🏳</div>
      <div class="place card">🏴</div>
      <div class="place card">🏴‍☠️</div>
      <div class="place card">🚩</div>
      <div class="place card">🌌</div>
      <div class="place card">🪐</div>
      <div class="place card">🌍</div>
      <div class="place card">🗻</div>
      <div class="place card">🌋</div>
      <div class="place card">⛰</div>
      <div class="place card">🏔</div>
      <div class="place card">🧭</div>
      <div class="place card">🗺</div>
      <div class="place card">🌏</div>
      <div class="place card">🌎</div>
      <div class="place card">🏟</div>
      <div class="place card">🏝</div>
      <div class="place card">🏜</div>
      <div class="place card">🏖</div>
      <div class="place card">🛣</div>
      <div class="place card">🏞</div>
      <div class="place card">🏕</div>
      <div class="place card">🛤</div>
      <div class="place card">⛪</div>
      <div class="place card">🏡</div>
      <div class="place card">🏠</div>
      <div class="place card">🏚</div>
      <div class="place card">🏙</div>
      <div class="place card">🏘</div>
      <div class="place card">🏗</div>
      <div class="place card">🏛</div>
      <div class="place card">🏤</div>
      <div class="place card">🏣</div>
      <div class="place card">🏢</div>
      <div class="place card">⛩</div>
      <div class="place card">🕍</div>
      <div class="place card">🛕</div>
      <div class="place card">🕌</div>
      <div class="place card">🕋</div>
      <div class="place card">🏭</div>
      <div class="place card">🕋</div>
      <div class="place card">🏬</div>
      <div class="place card">🏫</div>
      <div class="place card">🏪</div>
      <div class="place card">🏩</div>
      <div class="place card">🏨</div>
      <div class="place card">🏦</div>
      <div class="place card">🏥</div>
      <div class="place card">🎌</div>
      <div class="place card">🗾</div>
      <div class="place card">🗽</div>
      <div class="place card">🌉</div>
      <div class="place card">🗼</div>
      <div class="place card">🌉</div>
      <div class="place card">💒</div>
      <div class="place card">🏰</div>
      <div class="place card">🏯</div>
      <div class="place card">🌇</div>
      <div class="place card">🌆</div>
      <div class="place card">🌅</div>
      <div class="place card">🌄</div>
      <div class="place card">🌃</div>
      <div class="place card">⛺</div>
      <div class="place card">⛲</div>
      <div class="place card">🛋</div>
      <div class="place card">🛏</div>
      <div class="place card">🚪</div>
      <div class="place card">🪑</div>
      <div class="place card">🧳</div>
      <div class="place card">🛎</div>
      <div class="place card">💈</div>
      <div class="place card">🪒</div>
      <div class="place card">♨</div>
      <div class="place card">🧴</div>
      <div class="place card">🧽</div>
      <div class="place card">🧼</div>
      <div class="place card">🚿</div>
      <div class="place card">🛁</div>
      <div class="place card">🧻</div>
      <div class="place card">🚽</div>
      <div class="place card">🧯</div>
      <div class="place card">🧺</div>
      <div class="place card">🧹</div>
      <div class="place card">🧷</div>
    </div>
    <div id="card" ref="weather" @mouseover="show">
      <div class="weather card">☁</div>
      <div class="weather card">⛅</div>
      <div class="weather card">⛈</div>
      <div class="weather card">🌤</div>
      <div class="weather card">🌝</div>
      <div class="weather card">🌫</div>
      <div class="weather card">🌪</div>
      <div class="weather card">🌩</div>
      <div class="weather card">🌨</div>
      <div class="weather card">🌧</div>
      <div class="weather card">🌦</div>
      <div class="weather card">🌥</div>
      <div class="weather card">🌘</div>
      <div class="weather card">🌗</div>
      <div class="weather card">🌖</div>
      <div class="weather card">🌕</div>
      <div class="weather card">🌔</div>
      <div class="weather card">🌓</div>
      <div class="weather card">🌒</div>
      <div class="weather card">🌑</div>
      <div class="weather card">🌟</div>
      <div class="weather card">⭐</div>
      <div class="weather card">🌞</div>
      <div class="weather card">☀</div>
      <div class="weather card">🌜</div>
      <div class="weather card">🌛</div>
      <div class="weather card">🌚</div>
      <div class="weather card">🌙</div>
      <div class="weather card">☂</div>
      <div class="weather card">🌂</div>
      <div class="weather card">🌈</div>
      <div class="weather card">🌀</div>
      <div class="weather card">🌬</div>
      <div class="weather card">🌡</div>
      <div class="weather card">☄</div>
      <div class="weather card">🌠</div>
      <div class="weather card">💧</div>
      <div class="weather card">🔥</div>
      <div class="weather card">⛄</div>
      <div class="weather card">☃</div>
      <div class="weather card">❄</div>
      <div class="weather card">⚡</div>
      <div class="weather card">⛱</div>
      <div class="weather card">☔</div>
      <div class="weather card">🌊</div>
    </div>
    <div id="card" ref="cel" @mouseover="show">
      <div class="cel card">🎈</div>
      <div class="cel card">🎆</div>
      <div class="cel card">🎇</div>
      <div class="cel card">🧨</div>
      <div class="cel card">✨</div>
      <div class="cel card">🎉</div>
      <div class="cel card">🎊</div>
      <div class="cel card">🎃</div>
      <div class="cel card">🧧</div>
      <div class="cel card">🎑</div>
      <div class="cel card">🎐</div>
      <div class="cel card">🎏</div>
      <div class="cel card">🎎</div>
      <div class="cel card">🎍</div>
      <div class="cel card">🎋</div>
      <div class="cel card">🎄</div>
      <div class="cel card">🎡</div>
      <div class="cel card">🎠</div>
      <div class="cel card">🎫</div>
      <div class="cel card">🎟</div>
      <div class="cel card">🎞</div>
      <div class="cel card">🎗</div>
      <div class="cel card">🎁</div>
      <div class="cel card">🎀</div>
      <div class="cel card">🛒</div>
      <div class="cel card">🧶</div>
      <div class="cel card">🧵</div>
      <div class="cel card">🎨</div>
      <div class="cel card">🖼</div>
      <div class="cel card">🎭</div>
      <div class="cel card">🎪</div>
      <div class="cel card">🎢</div>
      <div class="cel card">👕</div>
      <div class="cel card">👔</div>
      <div class="cel card">🧥</div>
      <div class="cel card">🥼</div>
      <div class="cel card">🥽</div>
      <div class="cel card">🦺</div>
      <div class="cel card">🕶</div>
      <div class="cel card">👓</div>
      <div class="cel card">👘</div>
      <div class="cel card">🥻</div>
      <div class="cel card">👗</div>
      <div class="cel card">🧦</div>
      <div class="cel card">🧤</div>
      <div class="cel card">🧣</div>
      <div class="cel card">🩳</div>
      <div class="cel card">👖</div>
      <div class="cel card">🛍</div>
      <div class="cel card">👝</div>
      <div class="cel card">👜</div>
      <div class="cel card">👛</div>
      <div class="cel card">👙</div>
      <div class="cel card">🩱</div>
      <div class="cel card">🩲</div>
      <div class="cel card">👚</div>
      <div class="cel card">👢</div>
      <div class="cel card">👡</div>
      <div class="cel card">👠</div>
      <div class="cel card">🥿</div>
      <div class="cel card">🥾</div>
      <div class="cel card">👟</div>
      <div class="cel card">👞</div>
      <div class="cel card">🎒</div>
      <div class="cel card">💋</div>
      <div class="cel card">🎓</div>
      <div class="cel card">🎩</div>
      <div class="cel card">👒</div>
      <div class="cel card">⛑</div>
      <div class="cel card">🧢</div>
      <div class="cel card">👑</div>
      <div class="cel card">🩰</div>
    </div>
    <div id="card" ref="thing" @mouseover="show">
      <div class="thing card">🏐</div>
      <div class="thing card">🏀</div>
      <div class="thing card">🥎</div>
      <div class="thing card">⚾</div>
      <div class="thing card">⚽</div>
      <div class="thing card">💎</div>
      <div class="thing card">💍</div>
      <div class="thing card">💄</div>
      <div class="thing card">🎣</div>
      <div class="thing card">⛸</div>
      <div class="thing card">⛳</div>
      <div class="thing card">🥌</div>
      <div class="thing card">🎳</div>
      <div class="thing card">🎱</div>
      <div class="thing card">🏉</div>
      <div class="thing card">🏈</div>
      <div class="thing card">🥍</div>
      <div class="thing card">🏒</div>
      <div class="thing card">🥅</div>
      <div class="thing card">🛷</div>
      <div class="thing card">🎿</div>
      <div class="thing card">🛶</div>
      <div class="thing card">🎽</div>
      <div class="thing card">🤿</div>
    </div>
    <div id="card" ref="people" @mouseover="show">
      <div class="people card">👩</div>
    </div>
  </div>
</template>

<style scoped>
#card {
  margin-left: 188px;
}

#title {
  font-size: 50px;
}

.card {
  width: 200px;
  height: 200px;
  background-color: #fff;
  float: left;
  margin-top: 20px;
  margin-left: 33px;
  border-radius: 15px;
  transition: 0.2s;
  font-size: 80px;
  text-align: center;
  line-height: 200px;
  cursor: default;
}

.card:hover {
  box-shadow: 2px 3px 7px 1px rgba(0, 0, 0, 0.3);
}
</style>

<script>
import bus from "../eventBus.js";

export default {
  methods: {
    show() {
      bus.$on("share", (val) => {
        if (val == "1-1") {
          this.$refs.emoji.style.display = "block";
          this.$refs.animal.style.display = "none";
          this.$refs.food.style.display = "none";
          this.$refs.plant.style.display = "none";
          this.$refs.traffic.style.display = "none";
          this.$refs.place.style.display = "none";
          this.$refs.weather.style.display = "none";
          this.$refs.cel.style.display = "none";
          this.$refs.thing.style.display = "none";
          this.$refs.people.style.display = "none";
        } else if (val == "1-2") {
          this.$refs.emoji.style.display = "none";
          this.$refs.animal.style.display = "block";
          this.$refs.food.style.display = "none";
          this.$refs.plant.style.display = "none";
          this.$refs.traffic.style.display = "none";
          this.$refs.place.style.display = "none";
          this.$refs.weather.style.display = "none";
          this.$refs.cel.style.display = "none";
          this.$refs.thing.style.display = "none";
          this.$refs.people.style.display = "none";
        } else if (val == "2-2") {
          this.$refs.emoji.style.display = "none";
          this.$refs.animal.style.display = "none";
          this.$refs.food.style.display = "block";
          this.$refs.plant.style.display = "none";
          this.$refs.traffic.style.display = "none";
          this.$refs.place.style.display = "none";
          this.$refs.weather.style.display = "none";
          this.$refs.cel.style.display = "none";
          this.$refs.thing.style.display = "none";
          this.$refs.people.style.display = "none";
        } else if (val == "2-1") {
          this.$refs.emoji.style.display = "none";
          this.$refs.animal.style.display = "none";
          this.$refs.food.style.display = "none";
          this.$refs.plant.style.display = "block";
          this.$refs.traffic.style.display = "none";
          this.$refs.place.style.display = "none";
          this.$refs.weather.style.display = "none";
          this.$refs.cel.style.display = "none";
          this.$refs.thing.style.display = "none";
          this.$refs.people.style.display = "none";
        } else if (val == "3-1") {
          this.$refs.emoji.style.display = "none";
          this.$refs.animal.style.display = "none";
          this.$refs.food.style.display = "none";
          this.$refs.plant.style.display = "none";
          this.$refs.traffic.style.display = "block";
          this.$refs.place.style.display = "none";
          this.$refs.weather.style.display = "none";
          this.$refs.cel.style.display = "none";
          this.$refs.thing.style.display = "none";
          this.$refs.people.style.display = "none";
        } else if (val == "3-2") {
          this.$refs.emoji.style.display = "none";
          this.$refs.animal.style.display = "none";
          this.$refs.food.style.display = "none";
          this.$refs.plant.style.display = "none";
          this.$refs.traffic.style.display = "none";
          this.$refs.place.style.display = "block";
          this.$refs.weather.style.display = "none";
          this.$refs.cel.style.display = "none";
          this.$refs.thing.style.display = "none";
          this.$refs.people.style.display = "none";
        } else if (val == "3-3") {
          this.$refs.emoji.style.display = "none";
          this.$refs.animal.style.display = "none";
          this.$refs.food.style.display = "none";
          this.$refs.plant.style.display = "none";
          this.$refs.traffic.style.display = "none";
          this.$refs.place.style.display = "none";
          this.$refs.weather.style.display = "block";
          this.$refs.cel.style.display = "none";
          this.$refs.thing.style.display = "none";
          this.$refs.people.style.display = "none";
        } else if (val == "4-1") {
          this.$refs.emoji.style.display = "none";
          this.$refs.animal.style.display = "none";
          this.$refs.food.style.display = "none";
          this.$refs.plant.style.display = "none";
          this.$refs.traffic.style.display = "none";
          this.$refs.place.style.display = "none";
          this.$refs.weather.style.display = "none";
          this.$refs.cel.style.display = "block";
          this.$refs.thing.style.display = "none";
          this.$refs.people.style.display = "none";
        } else if (val == "4-2") {
          this.$refs.emoji.style.display = "none";
          this.$refs.animal.style.display = "none";
          this.$refs.food.style.display = "none";
          this.$refs.plant.style.display = "none";
          this.$refs.traffic.style.display = "none";
          this.$refs.place.style.display = "none";
          this.$refs.weather.style.display = "none";
          this.$refs.cel.style.display = "none";
          this.$refs.people.style.display = "none";
          this.$refs.thing.style.display = "block";
        } else if (val == "5") {
          this.$refs.emoji.style.display = "none";
          this.$refs.animal.style.display = "none";
          this.$refs.food.style.display = "none";
          this.$refs.plant.style.display = "none";
          this.$refs.traffic.style.display = "none";
          this.$refs.place.style.display = "none";
          this.$refs.weather.style.display = "none";
          this.$refs.cel.style.display = "none";
          this.$refs.thing.style.display = "none";
          this.$refs.people.style.display = "block";
        }
      });
    },
  },
};
</script>